apiVersion: v1
kind: Service
metadata:
  name: word-service
  namespace: word-database
spec:
  type: LoadBalancer
  selector:
    app: word-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
