version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
    environment:
      MYSQL_CONNECTION: user:Password@123@tcp(mysql:3306)/word_db
    ports:
      - "8080:8080"
    restart: always
